### ISSUE TITLE
es 2.x mapping upgrade issue

### ISSUE THREAD

**Issue by nellicus** [elastic/topbeat#44]
```
Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [topbeat-2015.09.20], reason: [Field name [proc.cpu] cannot contain '.']
Likely root cause: MapperParsingException[Field name [proc.cpu] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:283)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:137)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:368)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:242)
```

**Comment by monicasarbu** [comment]
This is fixed in master and it will be included with the next release, beta4.

**Comment by malinir123** [comment]
I have the following mapping in elasticsearch 1.1.1 and indexed the data.

           	"acronymfield" : {
            	"type" : "string",
            	"fields": {
            		"raw" : {
            			"type": "string",
            	 		"index": "not_analyzed"
            	 	 }
             	}	          
		    },
I was trying to upgrade to version 2.0 by starting elasticsearch2.0.

I still get the following error:

Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [csv3], reason: [Field name [acronymfield.raw] cannot contain '.']
Likely root cause: MapperParsingException[Field name [acronymfield.raw] cannot contain '.']
at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:283)
at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:137)
at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:368)
at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:242)
at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:329)
at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:112)
at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:226)
at org.elasticsearch.gateway.GatewayMetaState.(GatewayMetaState.java:85)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at <<>>
at org.elasticsearch.node.Node.(Node.java:198)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

Any ideas please? Is it complaining about the "." in the data that is being indexed?

**Comment by ruflin** [comment]
@malinir123 I looks like you have fields with a . inside in your old mappings. This was allowed in ES 1.* but is not compatible with ES 2.0: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

You could also try the migration-plugin to see if you have any other ES 2.0 compatibility problems: https://github.com/elastic/elasticsearch-migration

**Comment by monicasarbu** [comment]
@malinir123 What version of Topbeat are you using? There was a fix for this particular issue done in 1.0.0-beta4. So, any version greater than this should work.
